spring:
  profiles:
    active: prod
    include:
      - core
      - external
      - repository

kakao:
  authorize-url: https://kauth.kakao.com/oauth/authorize?response_type=code&client_id={0}&redirect_uri={1}
  app-key: ENC(la2O8hAJw/5PQXn8KxMXPDaAdnyXKBCGLZeI1uRkka+m2hbbtz+FmdQg3RE/B/aE)
  redirect-url: http://34.47.114.108:8080/api/kakao/login